source 'https://github.com/CocoaPods/Specs.git'

target 'LLAButton', :exclusive => true do
  pod "LLAButton", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "LLAButton", :path => "../"

  # pod 'Specta'
  # pod 'Expecta'
  # pod 'FBSnapshotTestCase'
  # pod 'Expecta+Snapshots'
end
